name: Task-2 DBT Workflow

on:
  push:
    branches:
      - task-2
  pull_request:
    branches:
      - main
      - dev

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dbt-postgres

      - name: Run dbt debug
        run: |
          dbt debug \
            --project-dir medical_warehouse \
            --profiles-dir medical_warehouse

      - name: Run dbt models
        run: |
          dbt run \
            --project-dir medical_warehouse \
            --profiles-dir medical_warehouse

      - name: Run dbt tests
        run: |
          dbt test \
            --project-dir medical_warehouse \
            --profiles-dir medical_warehouse

      - name: Generate dbt docs
        run: |
          dbt docs generate \
            --project-dir medical_warehouse \
            --profiles-dir medical_warehouse
